### ISSUE TITLE
Feature request: Support for AsyncAPI

### ISSUE THREAD

**Issue by LuisEgui** [HiDeoo/.github#10]
### Is your feature request related to a problem?

I'd like to have support for [AsyncAPI](https://www.asyncapi.com/en) schemas

### Describe the solution you'd like

It'd be nice when having both: openapi and asyncapi solutions when doing websockets and rest apis

**Comment by HiDeoo** [comment]
Thanks for your feedback :raised_hands: 

I'm assuming this was meant for the https://github.com/HiDeoo/starlight-openapi repo, not sure how it ended up here. 

Supporting both the OpenAPI & Swagger specifications is already pretty heavy, and by looking at the AsyncAPI spec (that I'm not familiar with), it seems like it would be a lot of work to support it as well considering the differences between the three. I'm leaning towards the idea that AsyncAPI could be an entirely dedicated project/plugin at the moment.

I'll keep it in mind for the future though and depending on the interest, I might consider it. Thanks for the suggestion!
